#!/usr/bin/env python3

import os
import shlex
import socket
import string
import subprocess
import sys
from collections.abc import Iterable
from typing import BinaryIO


def is_url(filename: str) -> bool:
    parts = filename.split("://", 1)
    if len(parts) < 2:
        return False
    # protocol prefix has no special characters => it's an URL
    allowed_symbols = string.ascii_letters + string.digits + "_"
    prefix = parts[0]
    return all(c in allowed_symbols for c in prefix)

def get_socket_path() -> str:
    if os.name == "nt":
        return r"\\.\pipe\udmpv"

    base_dir = (
        os.getenv("UDMPV_SOCKET_DIR") or
        os.getenv("XDG_RUNTIME_DIR") or
        os.getenv("HOME") or
        os.getenv("TMPDIR")
    )

    if not base_dir:
        raise Exception("Could not determine a base directory for the socket. "
                        "Ensure that one of the following environment variables is set: "
                        "UDMPV_SOCKET_DIR, XDG_RUNTIME_DIR, HOME or TMPDIR.")

    return os.path.join(base_dir, ".udmpv")

def send_files_to_dmpv(conn: socket.socket | BinaryIO, files: Iterable[str]) -> None:
    try:
        send = conn.send if isinstance(conn, socket.socket) else conn.write
        for f in files:
            f = f.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            send(f'raw loadfile "{f}" append-play\n'.encode())
    except Exception:
        print("dmpv is terminating or the connection was lost.", file=sys.stderr)
        sys.exit(1)

def start_dmpv(files: Iterable[str], socket_path: str) -> None:
    dmpv = "dmpv"
    dmpv_command = shlex.split(os.getenv("DMPV", dmpv))
    dmpv_command.extend([
        "--profile=pseudo-gui",
        f"--input-ipc-server={socket_path}",
        "--",
    ])
    dmpv_command.extend(files)
    subprocess.Popen(dmpv_command, start_new_session=True)

def main() -> None:
    files = (os.path.abspath(f) if not is_url(f) else f for f in sys.argv[1:])
    socket_path = get_socket_path()

    try:
        if os.name == "nt":
            with open(socket_path, "r+b", buffering=0) as pipe:
                send_files_to_dmpv(pipe, files)
        else:
            with socket.socket(socket.AF_UNIX) as sock:
                sock.connect(socket_path)
                send_files_to_dmpv(sock, files)
    except (FileNotFoundError, ConnectionRefusedError):
        start_dmpv(files, socket_path)

if __name__ == "__main__":
    main()
